import type { Product } from "./types";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const SEED_PRODUCTS: Product[] = [
  {
    id: "prod_001",
    name: "Rice (Sinandomeng)",
    category: "Grains",
    unit: "per kg",
    currentPrice: 54,
    targetPrice: 50,
    stockStatus: "in-stock",
    stockCount: 200,
    weeklyUnitsSold: 85,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(60),
    priceHistory: [
      { date: daysAgo(30), price: 48 },
      { date: daysAgo(21), price: 50 },
      { date: daysAgo(14), price: 52 },
      { date: daysAgo(7), price: 54 },
      { date: daysAgo(1), price: 54 },
    ],
  },
  {
    id: "prod_002",
    name: "Cooking Oil (1L)",
    category: "Condiments",
    unit: "1 bottle",
    currentPrice: 92.5,
    targetPrice: 88,
    stockStatus: "in-stock",
    stockCount: 48,
    weeklyUnitsSold: 32,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(55),
    priceHistory: [
      { date: daysAgo(30), price: 80 },
      { date: daysAgo(21), price: 85 },
      { date: daysAgo(14), price: 90 },
      { date: daysAgo(3), price: 92.5 },
    ],
  },
  {
    id: "prod_003",
    name: "Sugar (White)",
    category: "Staples",
    unit: "per kg",
    currentPrice: 88,
    targetPrice: 85,
    stockStatus: "in-stock",
    stockCount: 120,
    weeklyUnitsSold: 40,
    isFeatured: true,
    isPromo: false,
    addedDate: daysAgo(50),
    priceHistory: [
      { date: daysAgo(30), price: 82 },
      { date: daysAgo(14), price: 84 },
      { date: daysAgo(7), price: 86 },
      { date: daysAgo(1), price: 88 },
    ],
  },
  {
    id: "prod_004",
    name: "Canned Loaf (San Miguel)",
    category: "Canned Goods",
    unit: "150g",
    currentPrice: 32.5,
    targetPrice: 31,
    stockStatus: "in-stock",
    stockCount: 96,
    weeklyUnitsSold: 55,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(45),
    priceHistory: [
      { date: daysAgo(30), price: 34 },
      { date: daysAgo(14), price: 33.5 },
      { date: daysAgo(3), price: 32.5 },
    ],
  },
  {
    id: "prod_005",
    name: "Instant Noodles (Spicy)",
    category: "Snacks",
    unit: "Multipack (6 pcs)",
    currentPrice: 92,
    targetPrice: 85,
    stockStatus: "in-stock",
    stockCount: 60,
    weeklyUnitsSold: 78,
    isFeatured: false,
    isPromo: true,
    addedDate: daysAgo(40),
    priceHistory: [
      { date: daysAgo(30), price: 105 },
      { date: daysAgo(21), price: 100 },
      { date: daysAgo(7), price: 95 },
      { date: daysAgo(1), price: 92 },
    ],
  },
  {
    id: "prod_006",
    name: "3-in-1 Coffee Blend",
    category: "Beverages",
    unit: "Pack of 10",
    currentPrice: 78,
    targetPrice: 75,
    stockStatus: "low-stock",
    stockCount: 5,
    weeklyUnitsSold: 120,
    isFeatured: true,
    isPromo: false,
    addedDate: daysAgo(35),
    priceHistory: [
      { date: daysAgo(30), price: 85 },
      { date: daysAgo(14), price: 82 },
      { date: daysAgo(7), price: 80 },
      { date: daysAgo(1), price: 78 },
    ],
  },
  {
    id: "prod_007",
    name: "Farm Fresh Eggs (Dozen)",
    category: "Fresh",
    unit: "12 pcs",
    currentPrice: 210,
    targetPrice: 200,
    stockStatus: "in-stock",
    stockCount: 30,
    weeklyUnitsSold: 25,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(30),
    priceHistory: [
      { date: daysAgo(21), price: 195 },
      { date: daysAgo(14), price: 200 },
      { date: daysAgo(7), price: 205 },
      { date: daysAgo(1), price: 210 },
    ],
  },
  {
    id: "prod_008",
    name: "Dish Soap (500ml)",
    category: "Household",
    unit: "1 bottle",
    currentPrice: 55,
    targetPrice: 52,
    stockStatus: "low-stock",
    stockCount: 8,
    weeklyUnitsSold: 18,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(28),
    priceHistory: [
      { date: daysAgo(28), price: 52 },
      { date: daysAgo(14), price: 54 },
      { date: daysAgo(3), price: 55 },
    ],
  },
  {
    id: "prod_009",
    name: "Mineral Water (1.5L)",
    category: "Beverages",
    unit: "1 bottle",
    currentPrice: 25,
    targetPrice: 25,
    stockStatus: "in-stock",
    stockCount: 144,
    weeklyUnitsSold: 98,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(25),
    priceHistory: [
      { date: daysAgo(25), price: 23 },
      { date: daysAgo(14), price: 24 },
      { date: daysAgo(7), price: 25 },
    ],
  },
  {
    id: "prod_010",
    name: "Canned Sardines (in Tomato)",
    category: "Canned Goods",
    unit: "155g",
    currentPrice: 22.75,
    targetPrice: 22,
    stockStatus: "in-stock",
    stockCount: 200,
    weeklyUnitsSold: 65,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(22),
    priceHistory: [
      { date: daysAgo(22), price: 24 },
      { date: daysAgo(14), price: 23.5 },
      { date: daysAgo(7), price: 23 },
      { date: daysAgo(1), price: 22.75 },
    ],
  },
  {
    id: "prod_011",
    name: "Premium Corned Beef",
    category: "Canned Goods",
    unit: "340g",
    currentPrice: 145,
    targetPrice: 140,
    stockStatus: "in-stock",
    stockCount: 48,
    weeklyUnitsSold: 22,
    isFeatured: false,
    isPromo: true,
    addedDate: daysAgo(20),
    priceHistory: [
      { date: daysAgo(20), price: 165 },
      { date: daysAgo(10), price: 155 },
      { date: daysAgo(3), price: 145 },
    ],
  },
  {
    id: "prod_012",
    name: "Laundry Powder (1kg)",
    category: "Household",
    unit: "1 pack",
    currentPrice: 95,
    targetPrice: 90,
    stockStatus: "in-stock",
    stockCount: 36,
    weeklyUnitsSold: 14,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(18),
    priceHistory: [
      { date: daysAgo(18), price: 88 },
      { date: daysAgo(10), price: 90 },
      { date: daysAgo(5), price: 95 },
    ],
  },
  {
    id: "prod_013",
    name: "Soy Sauce (350ml)",
    category: "Condiments",
    unit: "1 bottle",
    currentPrice: 38,
    targetPrice: 35,
    stockStatus: "in-stock",
    stockCount: 72,
    weeklyUnitsSold: 30,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(15),
    priceHistory: [
      { date: daysAgo(15), price: 36 },
      { date: daysAgo(7), price: 37 },
      { date: daysAgo(2), price: 38 },
    ],
  },
  {
    id: "prod_014",
    name: "Shampoo Sachet (Pack of 12)",
    category: "Personal Care",
    unit: "12 sachets",
    currentPrice: 60,
    targetPrice: 58,
    stockStatus: "low-stock",
    stockCount: 15,
    weeklyUnitsSold: 44,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(12),
    priceHistory: [
      { date: daysAgo(12), price: 65 },
      { date: daysAgo(5), price: 62 },
      { date: daysAgo(1), price: 60 },
    ],
  },
  {
    id: "prod_015",
    name: "Vinegar (350ml)",
    category: "Condiments",
    unit: "1 bottle",
    currentPrice: 28,
    targetPrice: 27,
    stockStatus: "in-stock",
    stockCount: 80,
    weeklyUnitsSold: 20,
    isFeatured: false,
    isPromo: false,
    addedDate: daysAgo(10),
    priceHistory: [
      { date: daysAgo(10), price: 26 },
      { date: daysAgo(5), price: 27 },
      { date: daysAgo(1), price: 28 },
    ],
  },
];
